#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR=$(dirname $0)

cat $DIR/README.md | grep -iIohE 'http(s?):\/\/[^ \"\(\)\<\>]*' | \
    xargs -n1 -P 10 curl -o /dev/null --silent --head --write-out '%{url_effective} %{http_code}\n' | \
    awk '$2 >= 400'

exit 0